2024-10-13 17:40:17,092 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Urban Universyty\pythonProject1\test\tests_12_4.py", line 71, in test_run
    r2 = Runner(2)
  File "D:\Urban Universyty\pythonProject1\test\tests_12_4.py", line 11, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-13 17:40:17,104 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Urban Universyty\pythonProject1\test\tests_12_4.py", line 60, in test_walk
    r1 = Runner('Вася', -5)
  File "D:\Urban Universyty\pythonProject1\test\tests_12_4.py", line 16, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
